"""Golden outputs are from the unmodified release candidate, not regenerated by tests."""
import json
from pathlib import Path
import pytest
from backend.tests.performance_cases import NOC_CASES, strategy_case
from app.services import noc_service, strategy_service

GOLDEN = Path(__file__).parent / "fixtures" / "performance_rc_4fa95a3.json"

@pytest.mark.parametrize("index", range(len(NOC_CASES)))
def test_noc_rc_parity(index):
    expected = json.loads(GOLDEN.read_text(encoding="utf-8"))
    assert noc_service.suggest_noc_matches(**NOC_CASES[index]) == expected["noc"][index]

@pytest.mark.parametrize("index", range(2))
def test_strategy_rc_parity(index, monkeypatch):
    monkeypatch.setattr(strategy_service, "generate_ai_strategy", lambda **kwargs: {})
    profile, language, members, case = strategy_case(index)
    actual = strategy_service.build_strategy(profile, language, members, case)
    expected = json.loads(GOLDEN.read_text(encoding="utf-8"))
    assert actual.pop("ai_status") == "unavailable"
    assert actual.pop("ai_strategy") is None
    assert expected["strategy"][index].pop("ai_strategy") == ""
    # Internal cached dataset tokens are sets; canonicalize only their JSON representation.
    assert json.loads(json.dumps(actual, default=sorted)) == expected["strategy"][index]
