"""add upload fields to client_documents

Revision ID: 0a8e716e0040
Revises: 0f98882e3384
Create Date: 2026-03-20 14:05:39.964886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a8e716e0040'
down_revision: Union[str, Sequence[str], None] = '0f98882e3384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('matter_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('target_program', sa.String(), nullable=True),
    sa.Column('country_of_residence', sa.String(), nullable=True),
    sa.Column('inside_canada', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('intake_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('eligibility_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matters_client_id'), 'matters', ['client_id'], unique=False)
    op.create_index(op.f('ix_matters_id'), 'matters', ['id'], unique=False)
    op.create_index(op.f('ix_matters_matter_type'), 'matters', ['matter_type'], unique=False)
    op.create_index(op.f('ix_matters_owner_user_id'), 'matters', ['owner_user_id'], unique=False)
    op.add_column('client_documents', sa.Column('matter_id', sa.Integer(), nullable=True))
    op.add_column('client_documents', sa.Column('document_type', sa.String(), nullable=True))
    op.add_column('client_documents', sa.Column('required', sa.Boolean(), nullable=False))
    op.add_column('client_documents', sa.Column('generated_from_matter', sa.Boolean(), nullable=False))
    op.add_column('client_documents', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('client_documents', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('client_documents', sa.Column('file_url', sa.String(), nullable=True))
    op.add_column('client_documents', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('client_documents', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('client_documents', sa.Column('verified_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_client_documents_matter_id'), 'client_documents', ['matter_id'], unique=False)
    op.create_foreign_key(None, 'client_documents', 'matters', ['matter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_documents', type_='foreignkey')
    op.drop_index(op.f('ix_client_documents_matter_id'), table_name='client_documents')
    op.drop_column('client_documents', 'verified_by')
    op.drop_column('client_documents', 'verified_at')
    op.drop_column('client_documents', 'uploaded_at')
    op.drop_column('client_documents', 'file_url')
    op.drop_column('client_documents', 'file_path')
    op.drop_column('client_documents', 'file_name')
    op.drop_column('client_documents', 'generated_from_matter')
    op.drop_column('client_documents', 'required')
    op.drop_column('client_documents', 'document_type')
    op.drop_column('client_documents', 'matter_id')
    op.drop_index(op.f('ix_matters_owner_user_id'), table_name='matters')
    op.drop_index(op.f('ix_matters_matter_type'), table_name='matters')
    op.drop_index(op.f('ix_matters_id'), table_name='matters')
    op.drop_index(op.f('ix_matters_client_id'), table_name='matters')
    op.drop_table('matters')
    # ### end Alembic commands ###
