"""add matters table

Revision ID: 0f98882e3384
Revises: 6896f9168f58
Create Date: 2026-03-19 13:05:46.747282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f98882e3384'
down_revision: Union[str, Sequence[str], None] = '6896f9168f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('crs_score', sa.Integer(), nullable=True),
    sa.Column('programs', sa.JSON(), nullable=True),
    sa.Column('strategy', sa.JSON(), nullable=True),
    sa.Column('full_result', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.alter_column('client_documents', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('clients', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profiles', 'has_job_offer',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('profiles', 'has_canadian_experience',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('profiles', 'studied_in_canada',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'free'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'individual'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.alter_column('profiles', 'studied_in_canada',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('profiles', 'has_canadian_experience',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('profiles', 'has_job_offer',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clients', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'Active'::character varying"),
               existing_nullable=False)
    op.alter_column('client_documents', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'Not Started'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
