"""add self documents

Revision ID: 34351986a012
Revises: 65ae47d90475
Create Date: 2026-03-21 11:21:42.943467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34351986a012'
down_revision: Union[str, Sequence[str], None] = '65ae47d90475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('self_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('matter_type', sa.String(), nullable=False),
    sa.Column('document_key', sa.String(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_self_documents_document_key'), 'self_documents', ['document_key'], unique=False)
    op.create_index(op.f('ix_self_documents_id'), 'self_documents', ['id'], unique=False)
    op.create_index(op.f('ix_self_documents_matter_type'), 'self_documents', ['matter_type'], unique=False)
    op.create_index(op.f('ix_self_documents_user_id'), 'self_documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_self_documents_user_id'), table_name='self_documents')
    op.drop_index(op.f('ix_self_documents_matter_type'), table_name='self_documents')
    op.drop_index(op.f('ix_self_documents_id'), table_name='self_documents')
    op.drop_index(op.f('ix_self_documents_document_key'), table_name='self_documents')
    op.drop_table('self_documents')
    # ### end Alembic commands ###
