"""add self applications

Revision ID: ad36741bad2c
Revises: 0a8e716e0040
Create Date: 2026-03-20 20:04:36.199807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad36741bad2c'
down_revision: Union[str, Sequence[str], None] = '0a8e716e0040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('self_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('matter_type', sa.String(), nullable=False),
    sa.Column('intake_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('eligibility_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('forms_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checklist_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_self_applications_id'), 'self_applications', ['id'], unique=False)
    op.create_index(op.f('ix_self_applications_user_id'), 'self_applications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_self_applications_user_id'), table_name='self_applications')
    op.drop_index(op.f('ix_self_applications_id'), table_name='self_applications')
    op.drop_table('self_applications')
    # ### end Alembic commands ###
