from . import ai_routes
from . import auth_routes
from . import billing_routes
from . import client_document_routes
from . import client_profile_routes
from . import client_routes
from . import client_simulation_routes
from . import client_strategy_routes
from . import crs_routes
from . import disclosure_routes
from . import express_entry_routes
from . import journey_routes
from . import matter_routes
from . import profile_routes
from . import program_routes
from . import recommendation_routes
from . import self_document_routes
from . import self_routes
from . import simulation_scenarios_routes
from . import strategy_routes